
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: sf_customer_purchases
      description: "customer puchase orders"
      columns:
          - name: c_custkey
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: cumulative_orders_by_date
      description: "cumulative customer puchase orders"
      columns:
          - name: o_orderdate
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name : incremental_time

